export const pokeTypes = {
    normal: '⭕️',
    fighting: '🥊',
    flying: '🪽',
    poison: '☠️',
    ground: '🗾',
    rock: '🪨',
    bug: '🐞',
    ghost: '👻',
    steel: '🔨',
    fire: '🔥',
    water: '💦',
    grass: '🍀',
    electric: '⚡️',
    psychic: '💫',
    ice: '❄️',
    dragon: '🐲',
    dark: '😈',
    fairy: '♌️',
    unknown: '❓',
    shadow: '🌒',
}